Documentation changes for JOSS review
ISISNeutronMuon/quickBayes pull request #94
Opened 2024-06-10 08:36 UTC by AnthonyLim23

2024-06-18 09:21 UTC, mattpitkin commented
Hi @AnthonyLim23, thanks for your work on updating the docs. I'd suggest changing the first sentence of the introduction to be even more explicit, e.g., change " calculating Bayesian quantities " to something like  " calculating a quick approximation of the Bayesian evidence for use in model selection ".

2024-06-18 09:36 UTC, AnthonyLim23 commented
I should get a day to work on this next week, so I will update it then. It looks like I will get about 1 day every 3 weeks, I am sorry about the slow rate.

2025-02-05 15:52 UTC, jess-farmer reviewed
I think the content of these updates look good, just a couple of minor comments

2025-02-05 15:52 UTC, jess-farmer commented on docs/source/cf/MCMC.rst
> +The integral in equation :math:numref:`eq_int` typically requires a numerical method to evaluate it.
I think it's possibly worth writing out the integral again on this page, rather than linking back to the theory page?

2025-02-06 10:21 UTC, jess-farmer requested changes

2025-02-06 10:21 UTC, jess-farmer commented on docs/source/introduction.rst
> +Bayes theorem for the posteriror probability is
```suggestion
Bayes theorem for the posterior probability is
```

2025-02-06 10:21 UTC, jess-farmer commented on docs/source/cf/MCMC.rst
> +and typically requires a numerical method for its evaluation.
```suggestion
   P(D|M) = \int_\Omega P(D| \underline{\theta}, M)P( \underline{\theta}|M)\mathrm{d\underline{\theta}}
which typically requires a numerical method for its evaluation.
```
Just a suggestion, but I'd probably just change the wording here slightly and remove the full stop after the integral

2025-02-06 11:18 UTC, jess-farmer approved these changes

2025-02-06 11:18 UTC, merged